//
//  DashboardPresenter.swift
//  NarTask
//
//  Created by Nazrin Atayeva on 23.01.24.
//  Copyright (c) 2024 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol DashboardPresentationLogic
{
  func presentStories(response: Dashboard.Something.Response)
}

class DashboardPresenter: DashboardPresentationLogic
{
  weak var viewController: DashboardDisplayLogic?
  
  
  func presentStories(response: Dashboard.Something.Response)
  {
      var storyModels: [StoryModel] = []
      for storyResponse in response.stories.stories {
          storyModels.append(StoryModel(image: storyResponse.image))
      }
      
    let viewModel = Dashboard.Something.ViewModel(stories: storyModels)
    viewController?.displayStories(viewModel: viewModel)
  }
}
