//
//  DashboardInteractor.swift
//  NarTask
//
//  Created by Nazrin Atayeva on 23.01.24.
//  Copyright (c) 2024 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol DashboardBusinessLogic
{
  func doSomething(request: Dashboard.Something.Request)
}

protocol DashboardDataStore
{
  //var name: String { get set }
}

class DashboardInteractor: DashboardBusinessLogic, DashboardDataStore
{
  var presenter: DashboardPresentationLogic?
  var worker: DashboardWorker?
  //var name: String = ""
  
  // MARK: Do something
  
  func doSomething(request: Dashboard.Something.Request)
  {
    worker = DashboardWorker()
    worker?.doSomeWork()
    
    let response = Dashboard.Something.Response()
    presenter?.presentSomething(response: response)
  }
}
