//
//  DashboardViewController.swift
//  NarTask
//
//  Created by Nazrin Atayeva on 23.01.24.
//  Copyright (c) 2024 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import SnapKit

protocol DashboardDisplayLogic: AnyObject {
    func displaySomething(viewModel: Dashboard.Something.ViewModel)
}

class DashboardViewController: UIViewController, DashboardDisplayLogic {
    var interactor: DashboardBusinessLogic?
    var router: (NSObjectProtocol & DashboardRoutingLogic & DashboardDataPassing)?
    var mainView: DashboardView!
    
    
//    lazy var mainView: DashboardView = {
//        let view = DashboardView()
//        view.translatesAutoresizingMaskIntoConstraints = false
//        return view
//    }()
//    
    override func loadView() {
        super.loadView()
        self.view = mainView
//        view = UIView()
//        var mainView: DashboardView!
//        view.addSubview(mainView)
        
//        mainView.snp.makeConstraints { make in
//            make.edges.equalToSuperview()
//        }
    }
    
    override func viewDidLoad() {
        super.viewDidLoad()
//        navigationController?.isNavigationBarHidden = true
        mainView.storiesCollectionView.delegate = self
        mainView.storiesCollectionView.dataSource = self
        
        mainView.servicesGridView.delegate = self
        self.load()
    }
    

    
    func load() {
        let request = Dashboard.Something.Request()
        interactor?.doSomething(request: request)
    }
    
    func displaySomething(viewModel: Dashboard.Something.ViewModel) {
        //nameTextField.text = viewModel.name
    }
}

extension DashboardViewController: UICollectionViewDelegate, UICollectionViewDataSource {
    func collectionView(_ collectionView: UICollectionView, numberOfItemsInSection section: Int) -> Int {
        return collectionView == mainView.storiesCollectionView ? 10 : 0
        
    }
    
    func collectionView(_ collectionView: UICollectionView, cellForItemAt indexPath: IndexPath) -> UICollectionViewCell {
        guard collectionView == mainView.storiesCollectionView,
              let cell = collectionView.dequeueReusableCell(withReuseIdentifier: StoryCircleCell.reuseIdentifier, for: indexPath) as? StoryCircleCell else {
            return UICollectionViewCell()
        }
        
        cell.imageView.image = UIImage(named: "StoryImage")
        return cell
        
    }
}

//extension DashboardViewController: ServicesGridViewDelegate {
//    func didSelectService(_ service: ServiceType) {
//
////        navigationController?.pushViewController(FreeSMSConfigurator.configure(FreeSMSViewController()), animated: true)
//        print("service is tapped and working")
//    }
//}

extension DashboardViewController: ServicesGridViewDelegate {
    func didSelectService(_ service: ServiceType) {
        switch service {
        case .freeSMS:
            router?.routeToFreeSMS()
        case .balanceTransfer:
             router?.routeToBalanceTransfer()
        case .servicesAbroad:
            router?.routeToVAS()
        default:
            break
        }
//        print("service is tapped and working")
    }
}


