//
//  DashboardInteractor.swift
//  NarTask
//
//  Created by Nazrin Atayeva on 23.01.24.
//  Copyright (c) 2024 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol DashboardBusinessLogic
{
    func fetchStories(request: Dashboard.Something.Request)
}

protocol DashboardDataStore
{
    //var name: String { get set }
}

class DashboardInteractor: DashboardBusinessLogic, DashboardDataStore
{
    var presenter: DashboardPresentationLogic?
    var worker: DashboardWorker?
    
    // MARK: Do something
    
    func fetchStories(request: Dashboard.Something.Request)
    {
        worker = DashboardWorker()
        worker?.fetchStories(completion: { stories in
            let response = Dashboard.Something.Response(stories: stories)
            self.presenter?.presentStories(response: response)
        })
        
        
    }
}
