//
//  VASInteractor.swift
//  NarTask
//
//  Created by Nazrin Atayeva on 28.01.24.
//  Copyright (c) 2024 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol VASBusinessLogic
{
  func doSomething(request: VAS.Something.Request)
}

protocol VASDataStore
{
  //var name: String { get set }
}

class VASInteractor: VASBusinessLogic, VASDataStore
{
  var presenter: VASPresentationLogic?
  var worker: VASWorker?
  //var name: String = ""
  
  // MARK: Do something
  
  func doSomething(request: VAS.Something.Request)
  {
    worker = VASWorker()
    worker?.doSomeWork()
    
    let response = VAS.Something.Response()
    presenter?.presentSomething(response: response)
  }
}
