//
//  FreeSMSViewController.swift
//  NarTask
//
//  Created by Nazrin Atayeva on 26.01.24.
//  Copyright (c) 2024 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol FreeSMSDisplayLogic: AnyObject {
    func displaySomething(viewModel: FreeSMS.Something.ViewModel)
}

class FreeSMSViewController: UIViewController, FreeSMSDisplayLogic
{
    var interactor: FreeSMSBusinessLogic?
    var router: (NSObjectProtocol & FreeSMSRoutingLogic & FreeSMSDataPassing)?
    
    // MARK: Object lifecycle
    
    override init(nibName nibNameOrNil: String?, bundle nibBundleOrNil: Bundle?)
    {
        super.init(nibName: nibNameOrNil, bundle: nibBundleOrNil)
        setup()
    }
    
    required init?(coder aDecoder: NSCoder)
    {
        super.init(coder: aDecoder)
        setup()
    }
    
    // MARK: Setup
    
    private func setup()
    {
        let viewController = self
        let interactor = FreeSMSInteractor()
        let presenter = FreeSMSPresenter()
        let router = FreeSMSRouter()
        viewController.interactor = interactor
        viewController.router = router
        interactor.presenter = presenter
        presenter.viewController = viewController
        router.viewController = viewController
        router.dataStore = interactor
    }
    
    // MARK: Routing
    
    override func prepare(for segue: UIStoryboardSegue, sender: Any?)
    {
        if let scene = segue.identifier {
            let selector = NSSelectorFromString("routeTo\(scene)WithSegue:")
            if let router = router, router.responds(to: selector) {
                router.perform(selector, with: segue)
            }
        }
    }
    
    // MARK: View lifecycle
    
    override func viewDidLoad()
    {
        super.viewDidLoad()
        setupNavigationBar()
        setupUI()
        load()
    }
    
    private func setupUI() {
        view.backgroundColor = ColorStyle.bgColor.load()
    }
    
    private func setupNavigationBar() {
        // Create an instance of UINavigationBarAppearance
        let appearance = UINavigationBarAppearance()
        appearance.configureWithOpaqueBackground()
        
        // Set the background color to white
        appearance.backgroundColor = .white
        
        // Customize the title text attributes to be pink
        appearance.titleTextAttributes = [.foregroundColor: UIColor.black]
        
        // Customize the large title text attributes if needed
        appearance.largeTitleTextAttributes = [.foregroundColor: UIColor.black]
        
        // Apply the appearance to the navigation bar
        navigationController?.navigationBar.standardAppearance = appearance
        navigationController?.navigationBar.scrollEdgeAppearance = appearance
        
        // If you want the bar to be non-translucent
        navigationController?.navigationBar.isTranslucent = false
        
        // Set the navigation item's title
        navigationItem.title = "Pulsuz SMS"
        
        // If you want to set a custom back button
        let backButtonImage = UIImage(named: "backBtn") // Use the correct system name for your image
            let backButton = UIBarButtonItem(image: backButtonImage, style: .plain, target: self, action: #selector(backButtonTapped))
            backButton.tintColor = UIColor.black
            navigationItem.leftBarButtonItem = backButton
    }
    
    
    @objc private func backButtonTapped() {
        navigationController?.popViewController(animated: true)
    }
    
    // MARK: Do something
    
    //@IBOutlet weak var nameTextField: UITextField!
    
    func load()
    {
        let request = FreeSMS.Something.Request()
        interactor?.doSomething(request: request)
    }
    
    func displaySomething(viewModel: FreeSMS.Something.ViewModel)
    {
        //nameTextField.text = viewModel.name
    }
    

}
