//
//  BalanceTransferInteractor.swift
//  NarTask
//
//  Created by Nazrin Atayeva on 28.01.24.
//  Copyright (c) 2024 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol BalanceTransferBusinessLogic
{
  func doSomething(request: BalanceTransfer.Something.Request)
}

protocol BalanceTransferDataStore
{
  //var name: String { get set }
}

class BalanceTransferInteractor: BalanceTransferBusinessLogic, BalanceTransferDataStore
{
  var presenter: BalanceTransferPresentationLogic?
  var worker: BalanceTransferWorker?
  //var name: String = ""
  
  // MARK: Do something
  
  func doSomething(request: BalanceTransfer.Something.Request)
  {
    worker = BalanceTransferWorker()
    worker?.doSomeWork()
    
    let response = BalanceTransfer.Something.Response()
    presenter?.presentSomething(response: response)
  }
}
